# Generated by Django 3.0.7 on 2020-06-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('sm1', models.IntegerField()),
                ('sm2', models.IntegerField()),
                ('sm3', models.IntegerField()),
            ],
        ),
    ]
